### ISSUE TITLE
how to reproduce the result in readme?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [leftthomas/NormSoftmax#3]
hi @leftthomas 
thanks for releasing the code, and it has good result in reamde. but i train the cub, only get `Test Epoch 31/31 R@1:55.87%[55.27%] R@2:68.89%[68.45%] R@4:79.66%[79.25%] R@8:88.10%[87.31%]`.  can u tell me how to reproduce the result u publish? below is my training command: `python train.py --feature_dim 2048 --data_path . --data_name cub`
thanks

**Comment by leftthomas** [comment]
@zimenglan-sysu-512 you need use the same hyper-parameters as readme
